channels:
  - defaults
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - numpy=1.17.2 # so we get the mkl libs as well
  - pip:
    - pytest==4.6.3
    - pylint==2.3.1
    - flask==2.0.2
    - gunicorn==20.0.4
    - imutils==0.5.4
    - opencv-contrib-python==4.5.4.60
    - tensorflow==2.6.2
    - Pillow==8.4.0